# Generated by "capnp id"
@0xd80f1201407bb2e9;

interface StreamService {
  reqReply @0 () -> (reqSvc :RequestCallback);

  interface RequestCallback {
    sendChunk @0 (chunk :Text) -> stream;
    done @1 (replySvc :ReplyCallback) -> ();
  }

  interface ReplyCallback {
    sendChunk @0 (chunk :Text) -> stream;
    done @1 ();
  }
}
