# Generated by "capnp id"
@0xdd07c66f09194693;

interface ReqReplyService {
  reqReply @0 (callback :ServerCallback) -> (callback :ClientCallback);

  interface ServerCallback {
    sendChunk @0 (chunk :Data) -> stream;
    done @1 ();
  }

  interface ClientCallback {
    sendChunk @0 (chunk :Data) -> stream;
    done @1 ();
  }
}
