# Generated by "capnp id"
@0xdd07c66f09194693;

interface StreamService {
  reqReply @0 () -> (reqSvc :RequestCallback);

  interface RequestCallback {
    sendChunk @0 (chunk :Data) -> stream;
    done @1 (replySvc :ReplyCallback) -> ();
  }

  interface ReplyCallback {
    sendChunk @0 (chunk :Data) -> stream;
    done @1 ();
  }
}
